-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 13:18:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user_emails
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_emails
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `user_emails` DEFAULT CHARACTER SET utf8 ;
USE `user_emails` ;

-- -----------------------------------------------------
-- Table `user_emails`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_emails`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emails` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
